gdjs.leaderboardCode = {};
gdjs.leaderboardCode.GDhero0Objects1= [];
gdjs.leaderboardCode.GDhero0Objects2= [];
gdjs.leaderboardCode.GDHeroObjects1= [];
gdjs.leaderboardCode.GDHeroObjects2= [];
gdjs.leaderboardCode.GDbackgearObjects1= [];
gdjs.leaderboardCode.GDbackgearObjects2= [];
gdjs.leaderboardCode.GDbackgear2Objects1= [];
gdjs.leaderboardCode.GDbackgear2Objects2= [];
gdjs.leaderboardCode.GDbackgear3Objects1= [];
gdjs.leaderboardCode.GDbackgear3Objects2= [];
gdjs.leaderboardCode.GDbackgear4Objects1= [];
gdjs.leaderboardCode.GDbackgear4Objects2= [];
gdjs.leaderboardCode.GDbackgear5Objects1= [];
gdjs.leaderboardCode.GDbackgear5Objects2= [];
gdjs.leaderboardCode.GDbackgear6Objects1= [];
gdjs.leaderboardCode.GDbackgear6Objects2= [];
gdjs.leaderboardCode.GDbackgear7Objects1= [];
gdjs.leaderboardCode.GDbackgear7Objects2= [];
gdjs.leaderboardCode.GDbackgear8Objects1= [];
gdjs.leaderboardCode.GDbackgear8Objects2= [];
gdjs.leaderboardCode.GDbackgear9Objects1= [];
gdjs.leaderboardCode.GDbackgear9Objects2= [];
gdjs.leaderboardCode.GDbackgear10Objects1= [];
gdjs.leaderboardCode.GDbackgear10Objects2= [];
gdjs.leaderboardCode.GDHero2Objects1= [];
gdjs.leaderboardCode.GDHero2Objects2= [];
gdjs.leaderboardCode.GDhero3Objects1= [];
gdjs.leaderboardCode.GDhero3Objects2= [];
gdjs.leaderboardCode.GDhero4Objects1= [];
gdjs.leaderboardCode.GDhero4Objects2= [];
gdjs.leaderboardCode.GDhero5Objects1= [];
gdjs.leaderboardCode.GDhero5Objects2= [];
gdjs.leaderboardCode.GDhero6Objects1= [];
gdjs.leaderboardCode.GDhero6Objects2= [];
gdjs.leaderboardCode.GDhero7Objects1= [];
gdjs.leaderboardCode.GDhero7Objects2= [];
gdjs.leaderboardCode.GDhero8Objects1= [];
gdjs.leaderboardCode.GDhero8Objects2= [];
gdjs.leaderboardCode.GDhero9Objects1= [];
gdjs.leaderboardCode.GDhero9Objects2= [];
gdjs.leaderboardCode.GDhealiconObjects1= [];
gdjs.leaderboardCode.GDhealiconObjects2= [];
gdjs.leaderboardCode.GDdustObjects1= [];
gdjs.leaderboardCode.GDdustObjects2= [];
gdjs.leaderboardCode.GDwallsObjects1= [];
gdjs.leaderboardCode.GDwallsObjects2= [];
gdjs.leaderboardCode.GDwalls2Objects1= [];
gdjs.leaderboardCode.GDwalls2Objects2= [];
gdjs.leaderboardCode.GDwalls3Objects1= [];
gdjs.leaderboardCode.GDwalls3Objects2= [];
gdjs.leaderboardCode.GDhero_95hitboxObjects1= [];
gdjs.leaderboardCode.GDhero_95hitboxObjects2= [];
gdjs.leaderboardCode.GDgoldObjects1= [];
gdjs.leaderboardCode.GDgoldObjects2= [];
gdjs.leaderboardCode.GDexpObjects1= [];
gdjs.leaderboardCode.GDexpObjects2= [];
gdjs.leaderboardCode.GDexptextObjects1= [];
gdjs.leaderboardCode.GDexptextObjects2= [];
gdjs.leaderboardCode.GDgunObjects1= [];
gdjs.leaderboardCode.GDgunObjects2= [];
gdjs.leaderboardCode.GDbulletObjects1= [];
gdjs.leaderboardCode.GDbulletObjects2= [];
gdjs.leaderboardCode.GDbonebulletObjects1= [];
gdjs.leaderboardCode.GDbonebulletObjects2= [];
gdjs.leaderboardCode.GDcursorObjects1= [];
gdjs.leaderboardCode.GDcursorObjects2= [];
gdjs.leaderboardCode.GDgunsmokeObjects1= [];
gdjs.leaderboardCode.GDgunsmokeObjects2= [];
gdjs.leaderboardCode.GDfadeObjects1= [];
gdjs.leaderboardCode.GDfadeObjects2= [];
gdjs.leaderboardCode.GDnameentryObjects1= [];
gdjs.leaderboardCode.GDnameentryObjects2= [];
gdjs.leaderboardCode.GDNewTextInputObjects1= [];
gdjs.leaderboardCode.GDNewTextInputObjects2= [];
gdjs.leaderboardCode.GDbloodhitObjects1= [];
gdjs.leaderboardCode.GDbloodhitObjects2= [];
gdjs.leaderboardCode.GDtextbgObjects1= [];
gdjs.leaderboardCode.GDtextbgObjects2= [];
gdjs.leaderboardCode.GDdemothankyouObjects1= [];
gdjs.leaderboardCode.GDdemothankyouObjects2= [];
gdjs.leaderboardCode.GDforestObjects1= [];
gdjs.leaderboardCode.GDforestObjects2= [];
gdjs.leaderboardCode.GDsnowshitObjects1= [];
gdjs.leaderboardCode.GDsnowshitObjects2= [];
gdjs.leaderboardCode.GDgunbadgeObjects1= [];
gdjs.leaderboardCode.GDgunbadgeObjects2= [];
gdjs.leaderboardCode.GDherobadgeObjects1= [];
gdjs.leaderboardCode.GDherobadgeObjects2= [];
gdjs.leaderboardCode.GDCreditsObjects1= [];
gdjs.leaderboardCode.GDCreditsObjects2= [];
gdjs.leaderboardCode.GDlockedObjects1= [];
gdjs.leaderboardCode.GDlockedObjects2= [];
gdjs.leaderboardCode.GDlocked2Objects1= [];
gdjs.leaderboardCode.GDlocked2Objects2= [];
gdjs.leaderboardCode.GDlocked3Objects1= [];
gdjs.leaderboardCode.GDlocked3Objects2= [];
gdjs.leaderboardCode.GDspecialinfoObjects1= [];
gdjs.leaderboardCode.GDspecialinfoObjects2= [];
gdjs.leaderboardCode.GDspecialinfo2Objects1= [];
gdjs.leaderboardCode.GDspecialinfo2Objects2= [];
gdjs.leaderboardCode.GDwarningObjects1= [];
gdjs.leaderboardCode.GDwarningObjects2= [];
gdjs.leaderboardCode.GDhotpelletsObjects1= [];
gdjs.leaderboardCode.GDhotpelletsObjects2= [];


gdjs.leaderboardCode.eventsList0 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = !(gdjs.evtTools.leaderboards.isLeaderboardViewLoaded());
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.popScene(runtimeScene);
}}

}


};

gdjs.leaderboardCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.leaderboardCode.GDhero0Objects1.length = 0;
gdjs.leaderboardCode.GDhero0Objects2.length = 0;
gdjs.leaderboardCode.GDHeroObjects1.length = 0;
gdjs.leaderboardCode.GDHeroObjects2.length = 0;
gdjs.leaderboardCode.GDbackgearObjects1.length = 0;
gdjs.leaderboardCode.GDbackgearObjects2.length = 0;
gdjs.leaderboardCode.GDbackgear2Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear2Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear3Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear3Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear4Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear4Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear5Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear5Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear6Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear6Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear7Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear7Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear8Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear8Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear9Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear9Objects2.length = 0;
gdjs.leaderboardCode.GDbackgear10Objects1.length = 0;
gdjs.leaderboardCode.GDbackgear10Objects2.length = 0;
gdjs.leaderboardCode.GDHero2Objects1.length = 0;
gdjs.leaderboardCode.GDHero2Objects2.length = 0;
gdjs.leaderboardCode.GDhero3Objects1.length = 0;
gdjs.leaderboardCode.GDhero3Objects2.length = 0;
gdjs.leaderboardCode.GDhero4Objects1.length = 0;
gdjs.leaderboardCode.GDhero4Objects2.length = 0;
gdjs.leaderboardCode.GDhero5Objects1.length = 0;
gdjs.leaderboardCode.GDhero5Objects2.length = 0;
gdjs.leaderboardCode.GDhero6Objects1.length = 0;
gdjs.leaderboardCode.GDhero6Objects2.length = 0;
gdjs.leaderboardCode.GDhero7Objects1.length = 0;
gdjs.leaderboardCode.GDhero7Objects2.length = 0;
gdjs.leaderboardCode.GDhero8Objects1.length = 0;
gdjs.leaderboardCode.GDhero8Objects2.length = 0;
gdjs.leaderboardCode.GDhero9Objects1.length = 0;
gdjs.leaderboardCode.GDhero9Objects2.length = 0;
gdjs.leaderboardCode.GDhealiconObjects1.length = 0;
gdjs.leaderboardCode.GDhealiconObjects2.length = 0;
gdjs.leaderboardCode.GDdustObjects1.length = 0;
gdjs.leaderboardCode.GDdustObjects2.length = 0;
gdjs.leaderboardCode.GDwallsObjects1.length = 0;
gdjs.leaderboardCode.GDwallsObjects2.length = 0;
gdjs.leaderboardCode.GDwalls2Objects1.length = 0;
gdjs.leaderboardCode.GDwalls2Objects2.length = 0;
gdjs.leaderboardCode.GDwalls3Objects1.length = 0;
gdjs.leaderboardCode.GDwalls3Objects2.length = 0;
gdjs.leaderboardCode.GDhero_95hitboxObjects1.length = 0;
gdjs.leaderboardCode.GDhero_95hitboxObjects2.length = 0;
gdjs.leaderboardCode.GDgoldObjects1.length = 0;
gdjs.leaderboardCode.GDgoldObjects2.length = 0;
gdjs.leaderboardCode.GDexpObjects1.length = 0;
gdjs.leaderboardCode.GDexpObjects2.length = 0;
gdjs.leaderboardCode.GDexptextObjects1.length = 0;
gdjs.leaderboardCode.GDexptextObjects2.length = 0;
gdjs.leaderboardCode.GDgunObjects1.length = 0;
gdjs.leaderboardCode.GDgunObjects2.length = 0;
gdjs.leaderboardCode.GDbulletObjects1.length = 0;
gdjs.leaderboardCode.GDbulletObjects2.length = 0;
gdjs.leaderboardCode.GDbonebulletObjects1.length = 0;
gdjs.leaderboardCode.GDbonebulletObjects2.length = 0;
gdjs.leaderboardCode.GDcursorObjects1.length = 0;
gdjs.leaderboardCode.GDcursorObjects2.length = 0;
gdjs.leaderboardCode.GDgunsmokeObjects1.length = 0;
gdjs.leaderboardCode.GDgunsmokeObjects2.length = 0;
gdjs.leaderboardCode.GDfadeObjects1.length = 0;
gdjs.leaderboardCode.GDfadeObjects2.length = 0;
gdjs.leaderboardCode.GDnameentryObjects1.length = 0;
gdjs.leaderboardCode.GDnameentryObjects2.length = 0;
gdjs.leaderboardCode.GDNewTextInputObjects1.length = 0;
gdjs.leaderboardCode.GDNewTextInputObjects2.length = 0;
gdjs.leaderboardCode.GDbloodhitObjects1.length = 0;
gdjs.leaderboardCode.GDbloodhitObjects2.length = 0;
gdjs.leaderboardCode.GDtextbgObjects1.length = 0;
gdjs.leaderboardCode.GDtextbgObjects2.length = 0;
gdjs.leaderboardCode.GDdemothankyouObjects1.length = 0;
gdjs.leaderboardCode.GDdemothankyouObjects2.length = 0;
gdjs.leaderboardCode.GDforestObjects1.length = 0;
gdjs.leaderboardCode.GDforestObjects2.length = 0;
gdjs.leaderboardCode.GDsnowshitObjects1.length = 0;
gdjs.leaderboardCode.GDsnowshitObjects2.length = 0;
gdjs.leaderboardCode.GDgunbadgeObjects1.length = 0;
gdjs.leaderboardCode.GDgunbadgeObjects2.length = 0;
gdjs.leaderboardCode.GDherobadgeObjects1.length = 0;
gdjs.leaderboardCode.GDherobadgeObjects2.length = 0;
gdjs.leaderboardCode.GDCreditsObjects1.length = 0;
gdjs.leaderboardCode.GDCreditsObjects2.length = 0;
gdjs.leaderboardCode.GDlockedObjects1.length = 0;
gdjs.leaderboardCode.GDlockedObjects2.length = 0;
gdjs.leaderboardCode.GDlocked2Objects1.length = 0;
gdjs.leaderboardCode.GDlocked2Objects2.length = 0;
gdjs.leaderboardCode.GDlocked3Objects1.length = 0;
gdjs.leaderboardCode.GDlocked3Objects2.length = 0;
gdjs.leaderboardCode.GDspecialinfoObjects1.length = 0;
gdjs.leaderboardCode.GDspecialinfoObjects2.length = 0;
gdjs.leaderboardCode.GDspecialinfo2Objects1.length = 0;
gdjs.leaderboardCode.GDspecialinfo2Objects2.length = 0;
gdjs.leaderboardCode.GDwarningObjects1.length = 0;
gdjs.leaderboardCode.GDwarningObjects2.length = 0;
gdjs.leaderboardCode.GDhotpelletsObjects1.length = 0;
gdjs.leaderboardCode.GDhotpelletsObjects2.length = 0;

gdjs.leaderboardCode.eventsList0(runtimeScene);

return;

}

gdjs['leaderboardCode'] = gdjs.leaderboardCode;
